## DATA PREPROCESSING AND DATA CLEANING

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('ICU.csv')
df.head()

,group,ID,outcome,age,gendera,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,1,125047,0.0,72,1,37.588179,0,0,0,1,...,138.750000,7.463636,109.166667,13.166667,2.618182,7.230,21.166667,0.5,40.0,55
1,1,139812,0.0,75,2,NaN,0,0,0,0,...,138.888889,8.162500,98.444444,11.444444,1.887500,7.225,33.444444,0.5,78.0,55
2,1,109787,0.0,83,2,26.572634,0,0,0,0,...,140.714286,8.266667,105.857143,10.000000,2.157143,7.268,30.571429,0.5,71.5,35
3,1,130587,0.0,43,2,83.264629,0,0,0,0,...,138.500000,9.476923,92.071429,12.357143,1.942857,7.370,38.571429,0.6,75.0,55
4,1,138290,0.0,75,2,31.824842,1,0,0,0,...,136.666667,8.733333,104.500000,15.166667,1.650000,7.250,22.000000,0.6,50.0,55

In [3]:
del df['ID']
del df['gendera']
del df['group']

In [4]:
df.tail()

,outcome,age,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,depression,Hyperlipemia,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
1172,0.0,62,25.516870,1,1,0,1,0,1,1,...,136.714286,10.271429,94.428571,20.142857,2.714286,NaN,27.714286,NaN,NaN,40
1173,0.0,78,25.822710,0,1,0,1,0,1,1,...,135.680000,10.523529,101.720000,18.160000,2.012500,NaN,20.480000,NaN,NaN,30
1174,0.0,85,23.891779,1,1,0,1,1,0,0,...,136.000000,8.466667,97.285714,14.000000,2.028571,NaN,28.857143,NaN,NaN,55
1175,0.0,79,35.288554,0,0,1,1,1,1,1,...,140.000000,8.183333,104.000000,15.750000,2.090000,NaN,24.375000,NaN,NaN,25
1176,0.0,47,23.121384,1,0,0,1,0,0,0,...,135.285714,9.085714,93.857143,20.285714,2.566667,NaN,26.571429,NaN,NaN,55

In [5]:
df.shape

(1177, 48)

In [6]:
df.size

56496

In [7]:
df.columns

Index(['outcome', 'age', 'BMI', 'hypertensive', 'atrialfibrillation',
       'CHD with no MI', 'diabetes', 'deficiencyanemias', 'depression',
       'Hyperlipemia', 'Renal failure', 'COPD', 'heart rate',
       'Systolic blood pressure', 'Diastolic blood pressure',
       'Respiratory rate', 'temperature', 'SP O2', 'Urine output',
       'hematocrit', 'RBC', 'MCH', 'MCHC', 'MCV', 'RDW', 'Leucocyte',
       'Platelets', 'Neutrophils', 'Basophils', 'Lymphocyte', 'PT', 'INR',
       'NT-proBNP', 'Creatine kinase', 'Creatinine', 'Urea nitrogen',
       'glucose', 'Blood potassium', 'Blood sodium', 'Blood calcium',
       'Chloride', 'Anion gap', 'Magnesium ion', 'PH', 'Bicarbonate',
       'Lactic acid', 'PCO2', 'EF'],
      dtype='object')

In [8]:
df.isnull()

,outcome,age,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,depression,Hyperlipemia,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
1173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
1174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
1175,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
1176,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False

In [9]:
print(df.isnull().sum())

outcome                       1
age                           0
BMI                         215
hypertensive                  0
atrialfibrillation            0
CHD with no MI                0
diabetes                      0
deficiencyanemias             0
depression                    0
Hyperlipemia                  0
Renal failure                 0
COPD                          0
heart rate                   13
Systolic blood pressure      16
Diastolic blood pressure     16
Respiratory rate             13
temperature                  19
SP O2                        13
Urine output                 36
hematocrit                    0
RBC                           0
MCH                           0
MCHC                          0
MCV                           0
RDW                           0
Leucocyte                     0
Platelets                     0
Neutrophils                 144
Basophils                   259
Lymphocyte                  145
PT                           20
INR                          20
NT-proBNP                     0
Creatine kinase             165
Creatinine                    0
Urea nitrogen                 0
glucose                      18
Blood potassium               0
Blood sodium                  0
Blood calcium                 1
Chloride                      0
Anion gap                     0
Magnesium ion                 0
PH                          292
Bicarbonate                   0
Lactic acid                 229
PCO2                        294
EF                            0
dtype: int64

In [10]:
df.fillna(df.median(), inplace=True)

In [11]:
print(df.isnull().sum())

outcome                     0
age                         0
BMI                         0
hypertensive                0
atrialfibrillation          0
CHD with no MI              0
diabetes                    0
deficiencyanemias           0
depression                  0
Hyperlipemia                0
Renal failure               0
COPD                        0
heart rate                  0
Systolic blood pressure     0
Diastolic blood pressure    0
Respiratory rate            0
temperature                 0
SP O2                       0
Urine output                0
hematocrit                  0
RBC                         0
MCH                         0
MCHC                        0
MCV                         0
RDW                         0
Leucocyte                   0
Platelets                   0
Neutrophils                 0
Basophils                   0
Lymphocyte                  0
PT                          0
INR                         0
NT-proBNP                   0
Creatine kinase             0
Creatinine                  0
Urea nitrogen               0
glucose                     0
Blood potassium             0
Blood sodium                0
Blood calcium               0
Chloride                    0
Anion gap                   0
Magnesium ion               0
PH                          0
Bicarbonate                 0
Lactic acid                 0
PCO2                        0
EF                          0
dtype: int64

In [12]:
df.head()

,outcome,age,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,depression,Hyperlipemia,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
0,0.0,72,37.588179,0,0,0,1,1,0,1,...,138.750000,7.463636,109.166667,13.166667,2.618182,7.230,21.166667,0.5,40.0,55
1,0.0,75,28.312474,0,0,0,0,1,0,0,...,138.888889,8.162500,98.444444,11.444444,1.887500,7.225,33.444444,0.5,78.0,55
2,0.0,83,26.572634,0,0,0,0,1,0,0,...,140.714286,8.266667,105.857143,10.000000,2.157143,7.268,30.571429,0.5,71.5,35
3,0.0,43,83.264629,0,0,0,0,0,0,0,...,138.500000,9.476923,92.071429,12.357143,1.942857,7.370,38.571429,0.6,75.0,55
4,0.0,75,31.824842,1,0,0,0,1,0,0,...,136.666667,8.733333,104.500000,15.166667,1.650000,7.250,22.000000,0.6,50.0,55

In [13]:
df['outcome'].unique()

array([0., 1.])

In [14]:
df.describe()

,outcome,age,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,depression,Hyperlipemia,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
count,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,...,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000,1177.000000
mean,0.135089,74.055225,29.845629,0.717927,0.451147,0.085811,0.421410,0.338997,0.118946,0.379779,...,138.890016,8.500893,102.283835,13.925094,2.120169,7.378896,26.911766,1.804118,44.902075,48.715378
std,0.341964,13.434061,8.461626,0.450200,0.497819,0.280204,0.493995,0.473570,0.323863,0.485538,...,4.151347,0.572019,5.339733,2.652732,0.251532,0.058371,5.167512,0.888536,11.062908,12.868436
min,0.000000,19.000000,13.346801,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,114.666667,6.700000,80.266667,6.636364,1.400000,7.090000,12.857143,0.500000,18.750000,15.000000
25%,0.000000,65.000000,25.276974,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,136.666667,8.150000,99.000000,12.250000,1.955556,7.350000,23.454545,1.300000,39.000000,40.000000
50%,0.000000,77.000000,28.312474,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,139.250000,8.500000,102.500000,13.666667,2.092308,7.380000,26.500000,1.600000,43.000000,55.000000
75%,0.000000,85.000000,32.101349,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,...,141.600000,8.868750,105.571429,15.416667,2.241667,7.410000,29.875000,2.000000,47.272727,55.000000
max,1.000000,99.000000,104.970366,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,154.736842,10.950000,122.526316,25.500000,4.072727,7.580000,47.666667,8.333333,98.600000,75.000000

In [15]:
df.corr()

,outcome,age,BMI,hypertensive,atrialfibrillation,CHD with no MI,diabetes,deficiencyanemias,depression,Hyperlipemia,...,Blood sodium,Blood calcium,Chloride,Anion gap,Magnesium ion,PH,Bicarbonate,Lactic acid,PCO2,EF
outcome,1.000000,0.064270,-0.061673,-0.072635,0.101238,-0.014590,-0.050359,-0.099244,-0.060752,-0.053185,...,-0.065585,-0.183164,0.060355,0.229427,0.074202,-0.141625,-0.222608,0.225050,-0.032040,-0.024298
age,0.064270,1.000000,-0.352926,0.177060,0.291003,0.037594,-0.089103,0.015099,-0.094543,0.114893,...,0.104325,-0.009951,0.138015,-0.004426,0.088315,0.095472,-0.061130,0.005906,-0.110986,0.054400
BMI,-0.061673,-0.352926,1.000000,-0.027839,-0.109668,-0.056985,0.144721,-0.019281,0.027889,-0.012337,...,0.044685,0.091618,-0.168754,-0.108801,0.019576,-0.104240,0.264255,-0.076788,0.285718,0.050698
hypertensive,-0.072635,0.177060,-0.027839,1.000000,0.006757,0.010040,0.129649,-0.005795,-0.043798,0.225965,...,0.033276,0.080005,-0.018294,0.067535,0.000580,0.020574,0.011035,-0.019752,-0.006160,0.012697
atrialfibrillation,0.101238,0.291003,-0.109668,0.006757,1.000000,-0.003449,-0.013032,-0.097414,-0.058864,0.050439,...,-0.026506,0.019466,0.023312,0.049712,0.067448,0.041221,-0.071813,0.048253,-0.084759,0.011168
CHD with no MI,-0.014590,0.037594,-0.056985,0.010040,-0.003449,1.000000,0.008831,0.043327,0.046724,0.047766,...,-0.071097,0.021364,-0.056855,0.024763,0.016926,0.061641,-0.009349,0.003592,-0.062375,-0.146272
diabetes,-0.050359,-0.089103,0.144721,0.129649,-0.013032,0.008831,1.000000,0.061274,0.005329,0.133406,...,0.030363,0.077863,-0.028450,0.037494,0.017670,-0.019329,0.043975,0.025282,0.054260,-0.025660
deficiencyanemias,-0.099244,0.015099,-0.019281,-0.005795,-0.097414,0.043327,0.061274,1.000000,0.063983,0.027618,...,-0.008358,-0.048428,0.064916,-0.016435,0.025365,0.008732,-0.059061,-0.106069,-0.069513,-0.031596
depression,-0.060752,-0.094543,0.027889,-0.043798,-0.058864,0.046724,0.005329,0.063983,1.000000,0.042347,...,-0.028112,0.010822,-0.022527,-0.014719,-0.081429,0.070657,0.005984,-0.005532,-0.060946,-0.031249
Hyperlipemia,-0.053185,0.114893,-0.012337,0.225965,0.050439,0.047766,0.133406,0.027618,0.042347,1.000000,...,-0.066404,0.094463,-0.060642,0.036542,-0.012630,0.017303,-0.006911,0.022569,-0.055434,-0.064887
Renal failure,-0.108856,0.112246,-0.031719,0.193266,0.046120,0.025835,0.188646,0.149957,0.004649,0.097050,...,0.016412,0.102047,-0.006255,0.247680,0.146947,-0.040177,-0.093402,-0.101386,-0.020852,-0.101591
COPD,-0.047223,-0.004048,0.008966,0.015029,-0.046189,0.004162,-0.074879,-0.028314,-0.005820,-0.005299,...,0.052802,0.023574,-0.082823,-0.088162,0.035349,-0.143690,0.179810,-0.041847,0.231881,0.048550
heart rate,0.129404,-0.209307,-0.017787,-0.128183,-0.006854,-0.017182,-0.134743,-0.043604,0.055171,-0.071740,...,-0.061683,-0.124788,0.033147,0.017467,-0.099468,0.008257,-0.094398,0.167250,-0.099412,-0.083356
Systolic blood pressure,-0.132039,-0.029370,0.091342,0.142024,-0.117784,-0.085674,0.129853,0.045607,0.016487,-0.010846,...,0.121871,0.149347,-0.003045,-0.036555,-0.016320,0.079609,0.120099,-0.143720,0.076366,0.227001
Diastolic blood pressure,-0.086779,-0.343495,0.137537,-0.023070,-0.071887,-0.005965,-0.054882,-0.107292,0.088679,-0.040232,...,-0.002674,0.131703,-0.090877,0.021204,-0.072249,0.071008,0.078266,0.055662,0.002968,-0.133514
Respiratory rate,0.116798,-0.044125,-0.041461,-0.055842,-0.029413,0.006559,-0.094472,-0.034396,-0.009670,-0.026980,...,-0.012447,-0.005489,-0.037124,0.097725,0.000746,0.067942,-0.024879,0.117991,-0.058431,-0.060900
temperature,-0.092323,-0.211862,0.074194,0.016013,-0.156322,-0.061915,0.025467,0.009148,0.039910,-0.082405,...,0.083696,-0.108833,0.096861,-0.096559,-0.094726,0.098553,0.007220,-0.043772,-0.032479,0.048146
SP O2,-0.071084,0.057843,-0.165864,0.061977,0.057974,0.057297,0.068329,0.082997,0.026163,0.013739,...,-0.022669,-0.077241,0.151738,0.029309,-0.043394,0.024892,-0.191957,0.050308,-0.188516,-0.037062
Urine output,-0.170422,-0.249365,0.262689,-0.035351,-0.153823,0.011779,0.052102,-0.036296,0.024372,-0.010284,...,-0.000640,0.132849,-0.162269,-0.141291,-0.054951,0.132312,0.232679,-0.094511,0.082387,0.035324
hematocrit,-0.016786,-0.019583,0.119922,-0.028032,0.022021,0.003097,-0.067017,-0.362072,0.007739,0.029845,...,0.073984,0.252243,-0.151756,-0.015932,0.038773,-0.009528,0.220249,0.086647,0.138452,-0.095595
RBC,-0.024182,-0.053557,0.149862,-0.008640,0.016521,0.000317,-0.040542,-0.315511,0.000883,0.020696,...,0.044176,0.224670,-0.173060,0.006005,0.015584,0.006387,0.204921,0.110463,0.107503,-0.120677
MCH,0.013365,0.077017,-0.122072,-0.020672,-0.028576,0.016401,-0.122618,-0.074629,-0.023515,0.007401,...,-0.024498,-0.026583,0.095144,-0.001193,0.048426,0.042917,-0.118381,-0.056189,-0.091457,0.087449
MCHC,-0.031810,0.016170,-0.104642,0.019514,-0.080776,0.019619,-0.154644,-0.079895,-0.073360,0.004616,...,-0.151668,-0.063412,0.058643,0.067942,0.026744,0.146395,-0.231127,-0.018894,-0.276278,0.070109
MCV,0.034065,0.083819,-0.086976,-0.035798,0.011260,0.008009,-0.056745,-0.043775,0.013800,0.007788,...,0.056777,0.001646,0.082788,-0.041192,0.044655,-0.033365,-0.011772,-0.062525,0.048313,0.067681
RDW,0.148204,-0.046301,0.048540,-0.098594,0.073495,0.041779,0.060271,0.142856,0.010191,-0.079922,...,-0.038737,-0.126993,0.015599,0.115440,-0.013533,-0.072037,-0.099254,0.126224,0.010072,-0.071141
Leucocyte,0.208399,0.011029,-0.060050,0.029023,0.098511,-0.036210,-0.069841,-0.054406,0.010182,0.006841,...,-0.058935,-0.099408,0.018489,0.210129,0.050356,-0.029225,-0.169646,0.205608,-0.110499,0.006957
Platelets,-0.088413,-0.037388,-0.048289,0.026693,-0.029558,-0.018511,0.010923,0.064608,0.089847,-0.020889,...,-0.038391,0.082775,-0.090790,-0.005344,-0.013813,0.111347,0.072185,-0.073885,-0.016291,0.025290
Neutrophils,0.066262,0.125994,-0.083907,0.012117,0.117811,0.038622,-0.034896,0.000458,-0.022342,0.039988,...,0.031024,-0.044236,0.021823,0.001499,0.047881,0.028981,-0.002250,-0.046286,-0.004726,0.053032
Basophils,-0.024710,-0.076761,0.039187,-0.060275,-0.078211,-0.041763,-0.023525,-0.022623,-0.014184,-0.041706,...,-0.014275,0.025603,-0.034825,-0.001311,-0.007508,-0.005014,0.026437,-0.005664,0.037908,-0.026353
Lymphocyte,-0.129228,-0.125924,0.078545,0.011321,-0.117171,-0.030126,0.054634,0.001644,0.041702,-0.011435,...,0.019072,0.089395,-0.005389,-0.045730,-0.075891,-0.023832,0.046930,0.010417,0.026889,-0.047310
PT,0.141440,0.098177,-0.004829,-0.029225,0.315687,-0.011362,0.036189,-0.037163,-0.067839,0.041197,...,-0.051680,-0.083976,-0.015704,0.082405,0.054784,0.003967,-0.064658,0.179930,-0.022528,-0.122841
INR,0.145575,0.100693,-0.001695,-0.033528,0.309511,-0.011840,0.042122,-0.035722,-0.070859,0.032148,...,-0.040217,-0.077877,-0.007640,0.080436,0.061742,-0.008466,-0.062630,0.184908,-0.017235,-0.108379
NT-proBNP,0.120970,0.054536,-0.164895,0.007977,0.084345,0.009881,0.050074,0.046108,0.011306,0.042752,...,-0.068560,-0.055590,0.018266,0.362201,0.045036,-0.059198,-0.248421,0.073443,-0.153674,-0.207925
Creatine kinase,0.070700,-0.020105,0.035883,0.032146,0.006661,0.000381,0.046897,-0.026199,-0.023740,-0.021921,...,0.006936,-0.060883,0.038108,0.045633,0.002060,-0.027465,-0.054785,0.081062,-0.037497,-0.069276
Creatinine,0.045958,-0.081163,0.005518,0.077294,0.022110,-0.011279,0.130946,0.112001,-0.008032,0.014821,...,-0.073398,0.070761,-0.090897,0.576189,0.190454,-0.181862,-0.237186,-0.000390,-0.065961,-0.058899
Urea nitrogen,0.202917,0.106833,-0.017854,0.074039,0.108165,0.026090,0.179937,0.078653,-0.062743,0.040934,...,-0.011477,0.063999,-0.005344,0.523419,0.387121,-0.180986,-0.247350,0.021783,-0.047542,-0.105619
glucose,0.032471,-0.093268,0.122670,0.051597,-0.029402,0.050297,0.356571,0.018586,0.023139,0.114838,...,0.013555,0.041080,-0.038295,0.078430,0.106093,-0.045757,0.016457,0.131069,0.005895,-0.024017
Blood potassium,0.136696,-0.057468,0.040979,-0.014213,-0.017644,0.008643,0.111988,0.025445,-0.023229,-0.007024,...,-0.222102,0.062617,-0.108273,0.281622,0.173657,-0.310832,-0.129459,0.090212,0.094098,-0.078937
Blood sodium,-0.065585,0.104325,0.044685,0.033276,-0.026506,-0.071097,0.030363,-0.008358,-0.028112,-0.066404,...,1.000000,0.084230,0.628386,-0.180992,0.061502,-0.031225,0.221399,-0.133774,0.188677,0.140809
Blood calcium,-0.183164,-0.009951,0.091618,0.080005,0.019466,0.021364,0.077863,-0.048428,0.010822,0.094463,...,0.084230,1.000000,-0.246419,0.091715,0.121096,0.085166,0.280362,-0.065208,0.139826,-0.045696
Chloride,0.060355,0.138015,-0.168754,-0.018294,0.023312,-0.056855,-0.028450,0.064916,-0.022527,-0.060642,...,0.628386,-0.246419,1.000000,-0.041917,-0.034931,-0.102117,-0.516465,-0.008858,-0.321328,0.103746
Anion gap,0.229427,-0.004426,-0.108801,0.067535,0.049712,0.024763,0.037494,-0.016435,-0.014719,0.036542,...,-0.180992,0.091715,-0.041917,1.000000,0.164545,-0.116257,-0.589342,0.326652,-0.376839,-0.160631
Magnesium ion,0.074202,0.088315,0.019576,0.000580,0.067448,0.016926,0.017670,0.025365,-0.081429,-0.012630,...,0.061502,0.121096,-0.034931,0.164545,1.000000,-0.003325,0.015791,-0.001368,0.037377,-0.029291
PH,-0.141625,0.095472,-0.104240,0.020574,0.041221,0.061641,-0.019329,0.008732,0.070657,0.017303,...,-0.031225,0.085166,-0.102117,-0.116257,-0.003325,1.000000,0.117782,-0.097289,-0.415391,-0.026384
Bicarbonate,-0.222608,-0.061130,0.264255,0.011035,-0.071813,-0.009349,0.043975,-0.059061,0.005984,-0.006911,...,0.221399,0.280362,-0.516465,-0.589342,0.015791,0.117782,1.000000,-0.258636,0.679470,0.082538
Lactic acid,0.225050,0.005906,-0.076788,-0.019752,0.048253,0.003592,0.025282,-0.106069,-0.005532,0.022569,...,-0.133774,-0.065208,-0.008858,0.326652,-0.001368,-0.097289,-0.258636,1.000000,-0.243376,-0.157947
PCO2,-0.032040,-0.110986,0.285718,-0.006160,-0.084759,-0.062375,0.054260,-0.069513,-0.060946,-0.055434,...,0.188677,0.139826,-0.321328,-0.376839,0.037377,-0.415391,0.679470,-0.243376,1.000000,0.114675
EF,-0.024298,0.054400,0.050698,0.012697,0.011168,-0.146272,-0.025660,-0.031596,-0.031249,-0.064887,...,0.140809,-0.045696,0.103746,-0.160631,-0.029291,-0.026384,0.082538,-0.157947,0.114675,1.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1177 entries, 0 to 1176
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   outcome                   1177 non-null   float64
 1   age                       1177 non-null   int64
 2   BMI                       1177 non-null   float64
 3   hypertensive              1177 non-null   int64
 4   atrialfibrillation        1177 non-null   int64
 5   CHD with no MI            1177 non-null   int64
 6   diabetes                  1177 non-null   int64
 7   deficiencyanemias         1177 non-null   int64
 8   depression                1177 non-null   int64
 9   Hyperlipemia              1177 non-null   int64
 10  Renal failure             1177 non-null   int64
 11  COPD                      1177 non-null   int64
 12  heart rate                1177 non-null   float64
 13  Systolic blood pressure   1177 non-null   float64
 14  Diastolic blood pressure  1177 non-null   float64
 15  Respiratory rate          1177 non-null   float64
 16  temperature               1177 non-null   float64
 17  SP O2                     1177 non-null   float64
 18  Urine output              1177 non-null   float64
 19  hematocrit                1177 non-null   float64
 20  RBC                       1177 non-null   float64
 21  MCH                       1177 non-null   float64
 22  MCHC                      1177 non-null   float64
 23  MCV                       1177 non-null   float64
 24  RDW                       1177 non-null   float64
 25  Leucocyte                 1177 non-null   float64
 26  Platelets                 1177 non-null   float64
 27  Neutrophils               1177 non-null   float64
 28  Basophils                 1177 non-null   float64
 29  Lymphocyte                1177 non-null   float64
 30  PT                        1177 non-null   float64
 31  INR                       1177 non-null   float64
 32  NT-proBNP                 1177 non-null   float64
 33  Creatine kinase           1177 non-null   float64
 34  Creatinine                1177 non-null   float64
 35  Urea nitrogen             1177 non-null   float64
 36  glucose                   1177 non-null   float64
 37  Blood potassium           1177 non-null   float64
 38  Blood sodium              1177 non-null   float64
 39  Blood calcium             1177 non-null   float64
 40  Chloride                  1177 non-null   float64
 41  Anion gap                 1177 non-null   float64
 42  Magnesium ion             1177 non-null   float64
 43  PH                        1177 non-null   float64
 44  Bicarbonate               1177 non-null   float64
 45  Lactic acid               1177 non-null   float64
 46  PCO2                      1177 non-null   float64
 47  EF                        1177 non-null   int64
dtypes: float64(37), int64(11)
memory usage: 441.5 KB

In [17]:
pd.crosstab(df["temperature"], df["glucose"])

glucose,66.666667,69.100000,70.222222,73.857143,74.000000,74.166667,74.294118,75.000000,75.400000,75.714286,...,338.846154,339.909091,342.500000,345.200000,348.444444,349.666667,352.333333,365.750000,369.000000,414.100000
temperature,,,,,,,,,,,,,,,,,,,,,
33.250000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34.150725,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34.324074,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
34.605556,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
34.672223,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38.643518,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38.798889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38.905229,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39.087963,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
39.132478,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df1 = df.copy()

In [19]:
import inflection
import re

In [20]:
cols_old = df.columns

In [21]:
# Function to remove special characters and spaces
def clean_column_name(name):
    name = re.sub(r'[^\w\s]', '', name)  # Remove special characters
    name = name.replace(' ', '_')  # Replace spaces with underscores
    return name
snakecase = lambda x: inflection.underscore(x)
# Apply the cleaning function and then the snake case conversion
cols_cleaned = list(map(lambda x: snakecase(clean_column_name(x)), cols_old))

In [22]:
cols_cleaned

['outcome',
 'age',
 'bmi',
 'hypertensive',
 'atrialfibrillation',
 'chd_with_no_mi',
 'diabetes',
 'deficiencyanemias',
 'depression',
 'hyperlipemia',
 'renal_failure',
 'copd',
 'heart_rate',
 'systolic_blood_pressure',
 'diastolic_blood_pressure',
 'respiratory_rate',
 'temperature',
 'sp_o2',
 'urine_output',
 'hematocrit',
 'rbc',
 'mch',
 'mchc',
 'mcv',
 'rdw',
 'leucocyte',
 'platelets',
 'neutrophils',
 'basophils',
 'lymphocyte',
 'pt',
 'inr',
 'n_tpro_bnp',
 'creatine_kinase',
 'creatinine',
 'urea_nitrogen',
 'glucose',
 'blood_potassium',
 'blood_sodium',
 'blood_calcium',
 'chloride',
 'anion_gap',
 'magnesium_ion',
 'ph',
 'bicarbonate',
 'lactic_acid',
 'pco2',
 'ef']

In [23]:
# Replace the column names in the DataFrame
df1.columns = cols_cleaned

In [24]:
df1.columns

Index(['outcome', 'age', 'bmi', 'hypertensive', 'atrialfibrillation',
       'chd_with_no_mi', 'diabetes', 'deficiencyanemias', 'depression',
       'hyperlipemia', 'renal_failure', 'copd', 'heart_rate',
       'systolic_blood_pressure', 'diastolic_blood_pressure',
       'respiratory_rate', 'temperature', 'sp_o2', 'urine_output',
       'hematocrit', 'rbc', 'mch', 'mchc', 'mcv', 'rdw', 'leucocyte',
       'platelets', 'neutrophils', 'basophils', 'lymphocyte', 'pt', 'inr',
       'n_tpro_bnp', 'creatine_kinase', 'creatinine', 'urea_nitrogen',
       'glucose', 'blood_potassium', 'blood_sodium', 'blood_calcium',
       'chloride', 'anion_gap', 'magnesium_ion', 'ph', 'bicarbonate',
       'lactic_acid', 'pco2', 'ef'],
      dtype='object')

In [25]:
df1.groupby(["systolic_blood_pressure","diastolic_blood_pressure"]).groups

{(75.0, 40.5): [937], (76.97619048, 54.73809524): [530], (79.23076923, 49.41025641): [823], (80.6, 49.04): [780], (82.45454545, 55.45454545): [310], (85.05882353, 44.17647059): [842], (85.28125, 57.40625): [1040], (85.35714286, 59.44642857): [617], (85.59090909, 43.63636364): [1035], (85.59459459, 47.02702703): [798], (85.88571429, 55.88571429): [519], (85.95238095, 47.33333333): [676], (86.26086957, 52.47826087): [816], (86.63636364, 60.27272727): [604], (87.69387755, 48.95918367): [862], (88.0625, 53.5): [895], (88.19230769, 59.88461538): [261], (88.51515152, 55.45454545): [637], (88.76666667, 56.73333333): [553], (88.95454545, 58.45454545): [736], (89.2173913, 32.13043478): [69], (89.41666667, 42.16666667): [330], (89.82142857, 58.96428571): [890], (89.86956522, 54.60869565): [613], (90.16, 60.76): [340], (90.2, 45.52): [260], (90.44827586, 41.89655172): [880], (90.54761905, 56.4047619): [1099], (90.85714286, 38.95238095): [808], (90.86363636, 52.04545455): [325], (91.0, 66.56521739): [1050], (91.12195122, 52.58536585): [886], (91.35294118, 45.52941176): [198], (92.23076923, 46.0): [496], (92.38888889, 57.94444444): [825], (92.40740741, 55.66666667): [650], (92.48, 62.2): [670], (92.82758621, 48.20689655): [725], (93.12, 50.56): [101], (93.32142857, 52.46428571): [606], (93.41666667, 50.95833333): [877], (93.44, 54.0): [326], (93.58333333, 57.5): [1123], (93.72727273, 51.36363636): [165], (94.0, 50.68965517): [208], (94.0, 59.56521739): [342], (94.12, 56.6): [273], (94.23529412, 61.11764706): [311], (94.33333333, 64.81818182): [718], (94.40625, 58.0625): [465], (94.41666667, 62.45833333): [1175], (94.56, 47.52): [262], (94.59259259, 60.81481481): [560], (94.625, 62.29166667): [68], (94.64102564, 48.07692308): [957], (94.64705882, 42.17647059): [776], (94.72727273, 63.31818182): [995], (94.73333333, 56.68888889): [401], (94.80952381, 62.35714286): [256], (94.85106383, 49.96808511): [956], (94.88095238, 58.64285714): [592], (95.0, 54.57142857): [1085], (95.0, 57.125): [790], (95.02941176, 58.29411765): [953], (95.04545455, 58.0): [589], (95.17391304, 54.34782609): [661], (95.19230769, 50.69230769): [479], (95.26666667, 59.63333333): [549], (95.37037037, 67.51851852): [464], (95.4, 53.33333333): [41], (95.44444444, 60.25925926): [21], (95.48387097, 63.58064516): [188], (95.51785714, 47.17857143): [535], (95.51851852, 60.74074074): [1056], (95.6, 47.84): [203], (95.65957447, 59.19148936): [1051], (95.71428571, 62.53571429): [134], (95.75, 52.07142857): [207], (95.78571429, 51.37037037): [469], (95.84, 63.48): [294], (95.85714286, 48.28571429): [121], (96.03333333, 42.43333333): [904], (96.04545455, 50.18181818): [51], (96.06896552, 56.48275862): [761], (96.07142857, 72.67857143): [732], (96.1, 58.35): [45], (96.25, 49.875): [980], (96.3, 65.85): [485], (96.5, 53.27777778): [381], (96.53333333, 55.26666667): [442], (96.6, 57.56): [338], (96.60714286, 52.03571429): [365], (96.65517241, 53.93103448): [459], (96.75, 61.625): [660], (96.75, 68.25): [1078], (96.88888889, 57.63888889): [502], (96.93333333, 56.11111111): [361], (97.03225806, 58.19354839): [875], (97.04545455, 45.18181818): [1073], (97.13043478, 66.52173913): [1090], ...}

In [26]:
df1["outcome"].value_counts()

outcome
0.0    1018
1.0     159
Name: count, dtype: int64

In [27]:
pivot_table = pd.pivot_table(df1, values='age', index='renal_failure', columns='outcome', aggfunc='mean')

In [28]:
pivot_table

outcome              0.0        1.0
renal_failure
0              72.321600  75.934426
1              75.928753  77.243243

In [29]:
pd.Categorical(df1["chloride"]).describe()

             counts    freqs
categories
80.26666667       1  0.00085
85.41666667       1  0.00085
85.64285714       1  0.00085
86.06666667       1  0.00085
86.95454545       1  0.00085
...             ...      ...
117.0833333       1  0.00085
117.3157895       1  0.00085
117.3333333       1  0.00085
117.6666667       1  0.00085
122.5263158       1  0.00085

[675 rows x 2 columns]

In [30]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1172    False
1173    False
1174    False
1175    False
1176    False
Length: 1177, dtype: bool

In [31]:
sum(df.duplicated())

0